# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgboard', '0002_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='pic',
        ),
    ]
