# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgboard', '0006_auto_20161011_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='bump_thread',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
