# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgboard', '0007_thread_bump_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='bump_thread',
            field=models.IntegerField(default=0),
        ),
    ]
